### ISSUE TITLE
Fix errors in the tests for comparison between the master versions

### ISSUE THREAD

**Issue by ttrummel** [e2nIEE/pandapipes#103]
In test_release_control.py, some tests are not run in the various master versions. This is partly because the json file cannot be read with controllers in the network, and also because identifiers of the time series calculation have changed. In the case of the "from_json" problem, the io_utils.py and file_io.py in pandapipes and the io_utils.py in pandapower must be adjusted. In the following, the tests of test_release_control.py that pass and fail are listed:

develop

test_release_control_pipeflow_json		        passed
test_release_control_pipeflow_without_json	passed
test_release_control_ts_json			        failed -> from_json and run_timeseries_ppipe
test_release_control_ts_without_json		failed -> run_timeseries_ppipe

-----------------------------------------------------------------------------------------------

master version 0.1.2 (latest)

test_release_control_pipeflow_json		        passed
test_release_control_pipeflow_without_json	passed
test_release_control_ts_json			        failed -> from_json and run_timeseries_ppipe
test_release_control_ts_without_json		failed -> run_timeseries_ppipe

-----------------------------------------------------------------------------------------------

master version 0.1.1

test_release_control_pipeflow_json		        passed
test_release_control_pipeflow_without_json	passed
test_release_control_ts_json			        failed -> from_json
test_release_control_ts_without_json		passed

-----------------------------------------------------------------------------------------------

master version 0.1.0

test_release_control_pipeflow_json		        passed
test_release_control_pipeflow_without_json	passed
test_release_control_ts_json			        failed -> from_json
test_release_control_ts_without_json		passed

**Comment by jkisse** [comment]
As of the next release of pandapower/pandapipes, it should be possible to store controllers in a net.

**Comment by dlohmeier** [comment]
@SimonRubenDrauz did you check the tests? Probably with the convert_format function we can close this?

**Comment by jkisse** [comment]
solved by new convert_format function
