### ISSUE TITLE
Files are created when running tests

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#134]
When I run the tests in pandapipes locally, files are created in pandapipes.results. This should never happen! Please make sure to use temporary files where to save results when building tests. Can anyone tell me where they come from? I would like to remove them then...

**Comment by jkisse** [comment]
I think the files are created by the outputwriter during [test_time_series](https://github.com/e2nIEE/pandapipes/blob/4a1a77458195be1f3ab43b172be50f9fdd130df8/pandapipes/test/pipeflow_internals/test_time_series.py#L162).
At least I could not find a corresponding delete statement.

**Comment by jkisse** [comment]
resolved by #136
