### ISSUE TITLE
Warning in constant fluid property

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#160]
I am working with some constant properties for my current simulation example and am getting many warnings during the pipeflow, which state 'WARNING: One constant property has several input variables even though it is independent of these' . In the calculations, this is quite annoying, and there is nothing I could do about them except changing the logging level. Here's what happens internally:

- During the pipeflow, some properties like density or viscosity are requested in dependence of the temperature. This is intended behavior, as most fluids show a dependency, but in my case this behavior is simplified.
- Since the constant property does not depend on any variable, it raises this warning. However, it is impossible to change the pipeflow code to respect this aspect.

I would suggest to add a flag to the ConstantProperty class whether a warning should be displayed or not. And I would set it to False by default, as this is normal behavior.

**Comment by dcronbach** [comment]
I agree. This warning is also part of the RNG workshop tutorials. Although the warning is quite annoying, I think it demonstrates quite well how the fluid properties work.
