### ISSUE TITLE
Output in pipeflow

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#163]
When running a pipeflow, I think that most users are not very much interested about the displayed output. For me, it is a little annoying when running a number of simulations and having to search the whole output for some special information of interest that is completely going down in the flood of information from the pipeflow. If there is opposition to removing the output (about iterations, residual etc.), we might add an output mode to the options, that can be set to "verbose" if needed.

**Comment by jkisse** [comment]
I agree that the output is mostly rather a bit annoying than helpful. It can by adjusting the logger level `pandapipes.set_logger_level_pipeflow("WARN")` . I don't know what the default logger level is. Maybe it would be good to either set the default level to "warn" or to "info" and change the pipeflow logger messages from "info" to "debug" level.
