### ISSUE TITLE
Fix warning in tests

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapipes#177]
Specify dtypes in pd.Series to silence warnings pd.Series(dtype=float64)

e..g.:
```
openmodelica_comparison/test_water_openmodelica.py: 26 warnings
  /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandapipes/test/openmodelica_comparison/pipeflow_openmodelica_comparison.py:106: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
    v_diff_mean_valve = pd.Series()
```

**Comment by Pantherkralle** [comment]
Where exactly can I see those warnings? Running all tests, only 4 warnings where shown to me and were gone after processing 4 lines of code. Should I just add "dtype='float64'" in each pd.Series() lacking that argument I find in that file or should I run the tests somewhere else?

**Comment by jkisse** [comment]
Strangely, these warnings don't show up in my local environment, too (with pandas 1.0.4). Maybe the warning is introduced with pandas 1.1 and it is not yet available via anaconda.

Yes, I think it would be easiest if you could simply add dtype='float64' to the empty pd.Series() calls in pipeflow_openmodelica_comparison.py.

**Comment by jkisse** [comment]
Now we are down to 5/6 warnings instead of 144, thanks a lot!
