### ISSUE TITLE
Confusing error messages in case of non-convergence

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#188]
I just realized that when a pipeflow does not converge, two diverging error messages appear:

pandapipes.pipeflow - WARNING: Maximum number of iterations reached but hydraulics solver did not converge.
UserWarning: Pipeflow converged, however, the results are phyisically incorrect as pressure is at the nodes [  237.   280.   301. ... 85568. 85569. 85593.] are negative

The first is just a logger warning, the second one is a UserWarning without raising an exception. It occurs in the junction component model upon result extraction. This issue raises the question how to deal with non-convergence. How should the results be written into the tables? Should the result tables be deleted, filled with NaN-values or just filled with whatever values calculated?

**Comment by dlohmeier** [comment]
If the maximum number of iterations is reached, an exception should be raised. Results should be handled similar to pandapower. Maybe add a hint to the "_pit" entry in the logger warning.

**Comment by dlohmeier** [comment]
In pandapower the following happens:

- init_results is done before the algorithm (i.e. empty result tables)
- if the algorithm did not converge, a LoadFlowNotConverged exception is raised, the result tables are not changed anymore
- result extraction happens after that check, i.e. in case of no convergence, no results are extracted

I think that is not a bad idea and we should implement this in pandapipes as well.

**Comment by kbensafta** [comment]
Issue #337 seems to be on the same thread but ahead of this issue. Should therefore this issue be closed or transferred to discussion?

**Comment by dlohmeier** [comment]
Thanks for the hint, the suggestions are already implemented, so I will close this issue.
