### ISSUE TITLE
The basic example on the website causes an error (std_type)

### ISSUE THREAD

**Issue by Fraank-dash** [e2nIEE/pandapipes#209]
That's the basic example on the website:
`import pandapipes as pp`
` net = pp.create_empty_network(fluid="lgas") `
` j1 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 1")`
` j2 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 2")   ` 
` j3 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 3") `
` ext_grid = pp.create_ext_grid(net, junction=j1, p_bar=1.1, t_k=293.15, name="Grid Connection")`
` sink = pp.create_sink(net, junction=j3, mdot_kg_per_s=0.045, name="Sink")`
` pipe = pp.create_pipe(net, from_junction=j1, to_junction=j2, length_km=0.1, diameter_m=0.05, name="Pipe 1")`
` valve = pp.create_valve(net, from_junction=j2, to_junction=j3, diameter_m=0.05, opened=True, name="Valve 1")`

When i execute the code i get the following error message:
`    pipe = pp.create_pipe(net, from_junction=j1, to_junction=j2, length_km=0.1, diameter_m=0.05, name="Pipe 1")
TypeError: create_pipe() missing 1 required positional argument: 'std_type'`

the error persists, when i add "add_stdtypes=False (if i am not mistaken this option disables the "Standardtypes" for Pipelines, which is by default set to "True")
` net = pp.create_empty_network(fluid="lgas",add_stdtypes=False) `

I had to search for a standardpipeline in the library, delete the diameter and replace it with a std_type
`pipe = pp.create_pipe(net, from_junction=j1, to_junction=j2, length_km=0.1, std_type="200_GGG", name="Pipe 1")`

**Comment by SimonRubenDrauz** [comment]
Hi Frank,

thanks for the hint regaridng the basic example of the website. We need to change that.

Actually, the solution of your problem is to use pp.create_pipe_from_parameters instead of using pp.create_pipe. If you use this function instead, you shouldn't have that problem you addessed.

As explanation: pp.create_pipe is used, if you want to use a std_type. If you don't have a specific std_type, you use pp.create_pipe_from_parameters. It is done so, as pandapower is doing it alike.

Best regards,

Simon

**Comment by jkisse** [comment]
Thank you for pointing that out!
The example has been updated and should work now:
 import pandapipes as pp
 ```
net = pp.create_empty_network(fluid="lgas") 
 j1 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 1")
 j2 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 2")    
 j3 = pp.create_junction(net, pn_bar=1.05, tfluid_k=293.15, name="Junction 3") 
 ext_grid = pp.create_ext_grid(net, junction=j1, p_bar=1.1, t_k=293.15, name="Grid Connection")
 sink = pp.create_sink(net, junction=j3, mdot_kg_per_s=0.045, name="Sink")
 pipe = pp.create_pipe_from_parameters(net, from_junction=j1, to_junction=j2, length_km=0.1, diameter_m=0.05, name="Pipe 1")
 valve = pp.create_valve(net, from_junction=j2, to_junction=j3, diameter_m=0.05, opened=True, name="Valve 1")
```

Best, Jolando
