### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by dcronbach** [e2nIEE/pandapipes#219]
I think it is a good idea to update the tutorials section on our homepage. I created this issue mainly to remind myself to:

- Have a look at the first to heating tutorials. Do they make sense?
- Move any tutorials, which are currently only available in the documentation to the tutorials section on the homepage

@dlohmeier , @SimonRubenDrauz , @jkisse : In december, we created also some german tutorials for a workshop. Shall we we also create links for these german versions on the homepage?

**Comment by dcronbach** [comment]
Additional note: I had a brief look at the time series tutorial contained in the documentation section. This seems to basically be redundant to the time series tutorial contained in the tutorials section. I suggest to delete the one contained in the docs and add a link to the time series tutorial in the tutorials section of pandapipes.

It might be that we have to update the tutorial.

**Comment by dlohmeier** [comment]
Yes, the link to the German tutorials might be quite useful.

**Comment by dcronbach** [comment]
Another suggestion: The tutorial heating_network_example should be removed, because

- in comparison to the other heating tutorials, no new information is added
- the topology setup is confusing. The pump provides a pressure level, which is not modified by the heat exchanger. Usually, there would be friction losses in pipe 2, but these are not visible because of the connected external grid. In my opinion, there are too many components added for this small network.

**Comment by jkisse** [comment]
I am not sure if I understand the tutorials correctly. Why are there (mass-)sinks and sources? I thought sinks and sources are only valid in gas networks and drinking water networks, while in heating networks heat exchangers should be used. Instead, there is not even a heat exchanger in creating_a_heating_network.

Also, my understanding was that circulation_pumps are the right candidates for heating networks, but the "normal" pump is used here. 

At the moment, both tutorials could lead to more confusion than clarification on heat networks, I am afraid. 

Is there an easy script that can be used to create a tutorial for a net similar to the network in the pandapipes paper?
![grafik](https://user-images.githubusercontent.com/44288328/105970122-4e936280-6089-11eb-9e96-d4f982d16afd.png)

**Comment by dcronbach** [comment]
A grid like the one of the paper (more or less) was added some days ago and will be available with the next release. Besides the heating tutorial with the pump (which I suggested to remove), there is another one consisting basically of a T junction. This one can be added as a tutorial.

A circular pump is only necessary if the fluid is returning to the pump in a closed loop.

**Comment by dcronbach** [comment]
Jolando and me just discussed that another tutorial might be helpful describing the calculation mode sof pandapipes in general.

**Comment by dcronbach** [comment]
Instead of creating a new tutorial on the topic, I only modified the homepage description. This might already be enough. I will close this issue now and push the changes on friday.
