### ISSUE TITLE
Parts of the documentation are missing in the pypi package

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapipes#257]
Not all folders in the "doc" directory are included in the pypi package. Thus, if a user wants to build the documentation locally, it will likely be truncated. We very much recommend the online documentation on readthedocs.io (for [master ](https://pandapipes.readthedocs.io/en/latest/) or [develop](https://pandapipes.readthedocs.io/en/develop/)). 

If users want to build the documentation locally, it is recommended to download/checkout the repository directly from GitHub instead of the pypi package.

**Comment by SimonRubenDrauz** [comment]
A solution could be that we exclude the doc-folder from the pypi-zipped-package
