### ISSUE TITLE
circular_flow_in_a_district_heating_grid > network figure  error 

### ISSUE THREAD

**Issue by ggrrll** [e2nIEE/pandapipes#264]
Hi, 

it seems that in
https://github.com/e2nIEE/pandapipes/blob/develop/tutorials/circular_flow_in_a_district_heating_grid.ipynb
in the  figure junction 1 and 3 have been swapped, w.r.t how the network is build

`pp.create_pipe_from_parameters(net, from_junction=j0, to_junction=j1, ...`
and
`pp.create_pipe_from_parameters(net, from_junction=j2, to_junction=j3,...` 

not sure if it's prettier to change the figure or the code

**Comment by dcronbach** [comment]
Hi,

I modified the figure and also corrected the junction names. The corrected version will be pushed to the develop branch soon.

**Comment by ggrrll** [comment]
thanks for the fix!
