### ISSUE TITLE
pandapipes 0.40 missing line in 'networks\__init.py'

### ISSUE THREAD

**Issue by ladderup** [e2nIEE/pandapipes#265]
networks\__init__.py

from pandapipes.networks.simple_gas_networks import *
from pandapipes.networks.simple_water_networks import *
from pandapipes.networks.simple_heat_transfer_networks import * #is missing in 0.40

**Comment by ladderup** [comment]
I think there is also a small typo in the documentation regarding 'simple_heat_transfer_networks'

https://pandapipes.readthedocs.io/en/latest/networks/heat_transfer_networks/heat_transfer_networks.html#

>>> pandapipes.networks.simple_water_networks.heat_transfer_delta() #does not exist
>>> pandapipes.networks.simple_heat_transfer_networks.heat_transfer_delta()

**Comment by jkisse** [comment]
Thanks for the notification, I fixed it.
