### ISSUE TITLE
pipe heat transfer equation (docs)

### ISSUE THREAD

**Issue by ggrrll** [e2nIEE/pandapipes#276]
Hi, 

the eq. in https://pandapipes.readthedocs.io/en/latest/components/pipe/pipe_component.html#heat-transfer-mode
seems to be missing the surface factor   (`$\pi d l $` ) -- also, that would be rather a power transfer, right? (` $\dot{Q}$ `)

here 
https://github.com/e2nIEE/pandapipes/blob/17aad6382d6c7ee79216ea9bff9e452dbc49e72a/pandapipes/component_models/abstract_models/branch_models.py#L244

it seems well implemented -- if that's what you use

**Comment by dcronbach** [comment]
Hi ggrrll,

I can confirm this. The implementation included the facter pi*diameter, but this information, as well as the pipe length, was missing in the documentation. A changed version is currently under review and will be pushed to the develop branch soon.
Thanks for reporting this issue.

**Comment by ggrrll** [comment]
you're welcome ! -- thanks in advance for the fix

ps:  I think that redefining  `alpha` in the code 
https://github.com/e2nIEE/pandapipes/blob/17aad6382d6c7ee79216ea9bff9e452dbc49e72a/pandapipes/component_models/abstract_models/branch_models.py#L236

is a bit confusing... why don't you simply multiply everything in the formula? ( it's not a big deal...it's more a matter of coding practice...)
