### ISSUE TITLE
KeyError: bus with run_timeseries 

### ISSUE THREAD

**Issue by ggrrll** [e2nIEE/pandapipes#278]
Hi,

i am having the attached error with `run_timeseries` in pandapipes (I am trying to adapt the tutorial on time-series)

any idea?

thanks

ps:
pandapower 2.6.0
pandapipes 0.4.0

pps: it would be nice to have some doc in https://pandapower.readthedocs.io/en/latest/timeseries/output_writer.html :) -- thanks

the logs are in https://github.com/e2nIEE/pandapower/issues/1272

**Comment by jkisse** [comment]
Hi ggrrll,

in pandapipes, the buses are called "junctions". So the logging parameters of the output writer have to be changed accordingly. Did you do that already?
e.g., a pandapipes output writer could look like this
```
def create_output_writer(net, time_steps, output_dir):
    ow = OutputWriter(net, time_steps, output_path=output_dir, output_file_type=".xlsx", log_variables=list())
    # these variables are saved to the harddisk after / during the time series loop
    ow.log_variable('res_sink', 'mdot_kg_per_s')
    ow.log_variable('res_junction', 'p_bar')
    ow.log_variable('res_pipe', 'v_mean_m_per_s')
    return ow
```

**Comment by jkisse** [comment]
There is also a tutorial on time series in pandapipes https://github.com/e2nIEE/pandapipes/blob/develop/tutorials/simple_time_series_example.ipynb

**Comment by ggrrll** [comment]
yeah, I was starting indeed from that example

here are mine 
```python
log_variables = [('res_junction', 'p_bar'),
                 ('res_pipe', 'mdot_from_kg_per_s'),
                 ('res_heat_exchanger', 'mdot_from_kg_per_s'),
                 ('res_valve', 'mdot_kg_per_s'),
                 ('res_circ_pump_pressure', 'mdot_kg_per_s'),
                 ('res_ext_grid', 'mdot_kg_per_s')]
```

**Comment by kbensafta** [comment]
Should this issue be considered as closed?
