### ISSUE TITLE
extend UserWarning to hydraulics mode

### ISSUE THREAD

**Issue by ggrrll** [e2nIEE/pandapipes#283]
I have built a little example from  the circular_flow_in_a_district_heating_grid tutorial  where `plift_bar` in `create_circ_pump_const_pressure` is not enough to have flow at higher junctions (which have `height_m=20`)

```python
pp.create_circ_pump_const_pressure(net, from_junction=j0, to_junction=j1, p_bar=0.1,
                                   plift_bar=1, t_k=273.15+35, name='main_pump')
``` 

but I get this warning

https://github.com/e2nIEE/pandapipes/blob/b338a8ad30d6f519d50ffc41fc7a81b27cfa7574/pandapipes/component_models/junction_component.py#L114

only when I run `mode='all'` ...
I think that `pipeflow` should return the same in any mode -- right?

thanks

**Comment by SimonRubenDrauz** [comment]
Hey ggrrll,

I tried to reproduce your problem but was not able to. Maybe you can give us some more information. I try to explain what I did, maybe you can build upon that. But before I go into detail about what I did, first I would like to explain, what pandapipes is doing here.

If you run a pipeflow there are three different modes ('all', 'hydraulics', 'heat'). If you run 'all', both 'hydraulics' and 'heat' are conducted. Important to know is, that 'heat' depends on hydraulic results. If you as user don't pass any hydraulic results, 'heat' alone doesn't work. 

In case of 'hydraulics' the temperature at the junction is not changed. It is assumed they are fixed. So the resulting temperature is equal to the temperature given at the junction initially (defined in junctions and circ_pump).

![grafik](https://user-images.githubusercontent.com/42580302/126184558-eef62801-77ac-45a4-a2db-bcb4923cdcce.png)
![grafik](https://user-images.githubusercontent.com/42580302/126184456-fb824a9d-5085-433a-a1ac-0209420a53a9.png)

--------------------------------------------------------------------------------------------------------------------------------

![grafik](https://user-images.githubusercontent.com/42580302/126184209-3fbbe3e0-4eb7-4f82-86e8-b4c6e0c37b2c.png)

However, as soon as you choose 'all', you also want to determine the heat flows. The values given initially are just used as starting points for the Newton Raphson. 

![grafik](https://user-images.githubusercontent.com/42580302/126184833-e803b761-2be1-4755-895d-94b9a209cb1a.png)


The user warning, however, relates to the resulting pressure. As the pressure results are always absolute, negative values don't make sense physically, even though the Newton Raphson is able to find solutions. 

As you pass p_bar = 0.1 as pressure at the 'from_junction' value and say there is a pressure lift of 1 bar, the pressure at 'to_junction' is -0.9. As in both cases (mode 'all' and 'hydraulics', 'heat' is not possible without passing hydraulic results) the pressure is negative, therefore, also in both modes the warning is printed. Could it be possible, that you chose the 'heat' mode and passed hydraulic results by yourself?

**Comment by ggrrll** [comment]
ok, yeah, I am actually now getting the warnings in both mode ...so, forget it about (there might have been some overlaps with objects in notebook)

thanks for the explanation anyway!
