### ISSUE TITLE
FR: source / sink in simple_plot

### ISSUE THREAD

**Issue by ggrrll** [e2nIEE/pandapipes#285]
Hi, 

it would be nice to have also sources and sinks plotted by `simple_plot` 

(I might also have a look into it and eventually submit a PR)

**Comment by jkisse** [comment]
Hi, 
you can add sinks and sources to the plot by adding `plot_sinks=True, plot_sources=True` to the function call. You may also want to adjust the size of the symbols `(sink_size=1.0, source_size=1.0).` See also https://pandapipes.readthedocs.io/en/develop/plotting/simple_plot.html
Best, 
Jolando
