### ISSUE TITLE
Sign Heat Flow of Heat Exchanger

### ISSUE THREAD

**Issue by DLottis** [e2nIEE/pandapipes#37]
Hello all,

today I wrote the code for a heating network and was very confused because the signs of the heat in the model for the heat exchanger are defined in exactly the opposite way from what I intuitively assumed and there is no corresponding reference in the documentation. I would suggest reversing the definition. This would mean that positive heat flows go into the fluid in the network and negative flows out.

Best regards
Dennis

**Comment by SimonRubenDrauz** [comment]
Is explained in the documentation. We sticked to the pandapower convention. Positive means energy goes out and negative means energy goes into the network. We close the issue.
