### ISSUE TITLE
STANET Converter

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapipes#390]
The STANET Converter is currently on a separate branch ([stanet_conversion](https://github.com/e2nIEE/pandapipes/tree/stanet_conversion)) since a few things are still open / work in progress, before it can be merged into the develop branch:

- [ ] add proper docstrings (@EPrade) 
- [x] add chapter in documentation (@EPrade)
- [x] point out that only the conversion of gas networks has been tested exhaustively and conversion of heat networks is still experimental
- [x] explain which versions of pandapipes / STANET have been tested (@dlohmeier, German STANET Version)
- [x] add example / test net, e.g. simplified Schutterwald-network
- [x] add some more tests (@dlohmeier , @jkisse)
- [ ] ~~implement Sutherland property integral value function (@dlohmeier)~~
- [x] add pipe-valve component like in STANET (inside of the STANET converter, not as a general component) ([PR #412](https://github.com/e2nIEE/pandapipes/pull/412))
- [x] ensure, that the correct csv-encoding is used. Clarify the standard STANET csv encoding (ANSI or UTF8?) and adjust the read_csv accordingly. Maybe try...except to cover both encodings.

**Comment by kbensafta** [comment]
> 

I agreed with @EPrade that I will take care of the first two tasks.

**Comment by dlohmeier** [comment]
@kbensafta could you also integrate the third bullet point on the list once you have created the documentation? It's just one small note as stated there.

**Comment by kbensafta** [comment]
Of course !

**Comment by dlohmeier** [comment]
The Sutherland task has been removed, because somehow this property method is not used anywhere.

**Comment by dlohmeier** [comment]
What is our target for the coverage? Does anyone have additional test cases that we could apply the converter to? I added a test and thereby the coverage was probably increased significantly, but a lot of cases (especially conversion of many different component types) were not covered yet.
