### ISSUE TITLE
Documentation pressure_control missing

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapipes#414]
The documentation (read the docs) for the recently added [pressure controllers](https://github.com/e2nIEE/pandapipes/blob/d1ae8f0727c2fae7ce19e4c6066de9784a4dd1dc/pandapipes/create.py#L744) is missing.

**Comment by jkisse** [comment]
I think the [docstring](https://github.com/e2nIEE/pandapipes/blob/d1ae8f0727c2fae7ce19e4c6066de9784a4dd1dc/pandapipes/create.py#L748-L750) is also incorrect - it does not neccessarily have a constant mass flow, does it? @dlohmeier

**Comment by dlohmeier** [comment]
Hmm, that seems to be a mistake indeed.
