### ISSUE TITLE
Tutorial update necessary (circular_flow_in_a_district_heating_grid)

### ISSUE THREAD

**Issue by EPrade** [e2nIEE/pandapipes#498]
Since the circular pump function has been changed the function definitions in the "circular_flow_in_a_district_heating_grid" tutorial do not fulfill the new parameter requirements.

New notations/function parameters : 
def create_circ_pump_const_mass_flow(net, from_junction, to_junction, p_bar, mdot_kg_per_s,
                                     t_k=None, name=None, index=None, in_service=True,
                                     type="pt", **kwargs):

**Comment by jkisse** [comment]
On develop,[ return_ and flow_ junctions](https://github.com/e2nIEE/pandapipes/blob/develop/pandapipes/create.py#L771) are used, not from_ and to_junction. Apparently, this has already been updated accordingly in the tutorial

**Comment by dlohmeier** [comment]
Hmm, as far as I understand it, on [master](https://github.com/e2nIEE/pandapipes/blob/master/tutorials/circular_flow_in_a_district_heating_grid.ipynb), this is also implemented. Can you check again?

**Comment by EPrade** [comment]
The problem occurred on the transient_heat_transfer branch. I guess the cause is that the branch is behind the develop branch  and will be automatically resolved when merging?

**Comment by dlohmeier** [comment]
Yes, we should update it, as there have been so many changes lately.
