### ISSUE TITLE
Division by zero error for zero-length components in transient heat mode

### ISSUE THREAD

**Issue by clarapineau** [e2nIEE/pandapipes#516]
In the transient calculation (branch_models.py -> def calculate_derivatives_thermal()), there is a division by the component length. This means that when trying to calculate zero-length components such as valves, the following warning/error occurs:

RuntimeWarning: divide by zero encountered in divide
  branch_component_pit[:, JAC_DERIV_DT] = - rho * area * cp * v_init / length + alpha \
MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)
CalculationNotConverged at time step 0

**Comment by dlohmeier** [comment]
I think this has been fixed, right? @clarapineau @EPrade

**Comment by clarapineau** [comment]
Correct, the issue has been fixed.
