### ISSUE TITLE
Isentropic compression work for a pump is not calculated over absolute pressures

### ISSUE THREAD

**Issue by oporras** [e2nIEE/pandapipes#542]
**Describe the bug**
I´m using the pump component P2 with a gas (methane). A parallel calculation of the isentropic compressión power showed me that the results from the pump considered a pressure ratio computed wrongly over the manometric pressures.

**To Reproduce**
A very simple case code is attached to reproduce the bug. 
[test-isentropic-compression-methane.py.zip](https://github.com/e2nIEE/pandapipes/files/11780642/test-isentropic-compression-methane.py.zip)

**Expected behavior**
The expected value of the isentropic power of compression is 0.00683022 MW but the pandapipes results table reports 0.007752 MW.

**Python environment (please complete the following information):**
 - OS: MacOS Big Sur (11.7.6)
 - pandapipes version: 0-8-4

**Additional context**
I'm interested in using the pump component because I have the characteristic curve of the compressor.

**Comment by jkisse** [comment]
Hello @oporras, 
thank you very much for pointing this out. Indeed, the ambient pressure was not considered correctly in the pressure ratio. A hotfix is available [here ](https://github.com/e2nIEE/pandapipes/tree/hotfix_0.8.5) and will be released soon. 
Thanks for the example - would you allow us to include it as a unit test? The remaining deviation in your example is now < 0.2 %.

sidenote: please note that kappa is assumed as 1.4 (bi-atomic gas), thus the calculated power might be not 100 % accurate.

**Comment by oporras** [comment]
Hi @jkisse,
thank you for your answer and the hotfix. Of course, you can use my example as a unit test.

Speaking of heat capacity ratio, you could quickly and effortlessly improve the $\kappa$ value by calculating the estimate for ideal gases using this relationship:

$$C_p - C_v =R_s$$

then

$$\kappa =  \frac{C_p}{C_v}=\frac{1}{1-\frac{R_s}{C_p}}$$ 

where $R_s = R_u/M$ is the particular gas constant.  $Cp$ can be calculated at the normal temperature.

For example, for methane, this expression gives me a value of 1.3 for $\kappa$, a very acceptable estimate.

**Comment by oporras** [comment]
I would like to clarify my last comment: I computed $\kappa = 1.312$ for methane using the `NORMAL_TEMPERATURE`. However, this is a better estimate of 1.3, the expected value, than the value for bi-atomic gases.

**Comment by jkisse** [comment]
Good point, thanks a lot. I've added it to the PR

**Comment by oporras** [comment]
OK. If you include the ideal gas estimation for $\kappa$ in the code, the test with my example must be updated as I used the value for di-atomic gases instead.
