### ISSUE TITLE
Please refer to igraph instead of python-igraph

### ISSUE THREAD

**Issue by szhorvat** [e2nIEE/pandapipes#547]
Please refer to `igraph` instead of `python-igraph` in the following locations:

https://github.com/search?q=repo%3Ae2nIEE%2Fpandapipes%20python-igraph&type=code

Please see https://github.com/igraph/python-igraph/issues/699 for an explanation.

**Comment by dlohmeier** [comment]
Hello @szhorvat ,
thank you for the notification, we will take care of this!
Kind regards
