### ISSUE TITLE
bug in circular_flow_in_a_district_heating_grid.py tutorial

### ISSUE THREAD

**Issue by panosz** [e2nIEE/pandapipes#580]
**Describe the bug**
It seems that the pump is connected in a reverse order that it was intended.

**To Reproduce**
Run the tutorial and check the output of `net.res_pipe`. The temperatures of the junctions are not order as the corresponding text in the notebook describes. 

**Error message**
None

**Expected behavior**
The temperatures at the to-nodes should be lower than the temperatures at the from-node

**Screenshots**

**Python environment (please complete the following information):**
 - OS: linux
 - pandapipes version 0.8.5 (the tutorial is from commit https://github.com/e2nIEE/pandapipes/commit/97119d208dce551f6a4a8a65e3a8fa27dbd8be28)

**Additional context**
None

I believe this is solved by switching the junctions of the pump, i.e.
```python
    return_junction=j3, flow_junction=j0,
```

**Comment by dlohmeier** [comment]
Hi @panosz ,
thanks for the hint, I created a quick fix to be releases soon.
Regards
