### ISSUE TITLE
Pressure and velocity result evaluation

### ISSUE THREAD

**Issue by dcronbach** [e2nIEE/pandapipes#60]
Some suggestions to improve the evaluation of pressure and velocity values:

- If the results table is plotted, the p_bar value shows the relative pressure. At the moment, the function to retrieve internal pipe results returns absolute pressure values. I can change the behaviour of this function, but it might help to note that all displayed pressure values are relative by naming them, for example, "p_rel_bar". 

- The values in the pipe results for v_to and v_from are misleading, because if a pipe has several sections, the mean value of all v_to velocities of the pipe is computed. Of course, v_to should be the velocity of the last pipe section positioned before the next junction.

**Comment by lthurner** [comment]
> I can change the behaviour of this function, but it might help to note that all displayed pressure values are relative by naming them, for example, "p_rel_bar".

If the value is relative, it is no longer in bar, no? Why not p_pu? Is the per unit system, as it is used not common in pipe flow calculations?

**Comment by dlohmeier** [comment]
@dcronbach did you change the behavior wrt your second point? I think, this is just a bug and needs to be fixed asap.

**Comment by jkisse** [comment]
@dcronbach did your PR #99 solve these issues? If yes, I think you can close the issue

**Comment by dcronbach** [comment]
Issue can be closed now.
