### ISSUE TITLE
i/o: net compatibility between different ppi-versions

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapipes#63]
There should be a robust way to open old pandapipes nets that were stored with an earlier release, also when something changed, e.g. the fluid-property class or column names in the component tables.
As a first step, it might be a good idea to store the version number in the json file.
Also, some try-except clauses could help to restore as much as possible, even when particular components can not be loaded successfully.

pandapower faced a similar issue when 2.0 was released, we can have look how they solved it.

**Comment by jkisse** [comment]
For each release, one (or more) test networks with all components should be created. For these networks, test for loading the net and checking for consistency should be added to ensure save reading in future versions. Further, e.g. hooks for automated renaming can be created, if column names change from one version to another.

**Comment by jkisse** [comment]
Networks that are stored as json have to be updated (or update in I/O method) to account for the change in the headers ("Controller" ⇾ "Object"). Check how pandapower handles this [(convert_format)](https://github.com/e2nIEE/pandapower/blob/develop/pandapower/convert_format.py)

**Comment by dlohmeier** [comment]
We introduced a convert_format function. In some cases there might still be saved networks that don't use it properly, then please fix this manually (I did this for pandapipes networks).
