### ISSUE TITLE
Pressure in p_pu/Temperature in t_pu 

### ISSUE THREAD

**Issue by SimonRubenDrauz** [e2nIEE/pandapipes#67]
Check if it makes sense to run calculations in pu instead of absolute values. Also check if this makes sense for hydraulic and thermal calculcations.

**Comment by jkisse** [comment]
In the[ Julia GasModels documentation](https://lanl-ansi.github.io/GasModels.jl/stable/math-model/#Steady-State-Gas-Flow), I found this:
![grafik](https://user-images.githubusercontent.com/44288328/104750245-19ffdc80-5754-11eb-8ba7-62a0b7e836a6.png)

**Comment by dcronbach** [comment]
We cover this at the moment with the scaling factor. Because pandapower uses pu and we now also offer coupled simulations, it might make sense to change to pu also in pandapipes. 

For pure users of pandapipes, this might feel unconventional, I think.
